### ISSUE TITLE
com.plexapp.plugnis.viasat  Problem found

### ISSUE THREAD

**Issue by Bengt7jqb** [plexinc-plugins/Services.bundle#1002]
com.plexapp.plugins.viasat/URL/Viasat Play(ServiceCode.pys

Line #103 change to 
key = HTTPLiveStreamURL(data['streams']['hls'])
Froom
key = HTTPLiveStreamURL(GetClientDependentURL(data['streams']['hls']))
And video streams start to vork again

**Comment by meriko** [comment]
Yep! Fixed by @JeppeTh in https://github.com/plexinc-plugins/Services.bundle/pull/1001
