### ISSUE TITLE
Youku.com - broken playback

### ISSUE THREAD

**Issue by chriscurtis** [plexinc-plugins/Services.bundle#745]
(Reported via twitter) Video is found and added to the Queue, but cannot be played. Example vid: http://v.youku.com/v_show/id_XNzE0Nzc3MzMy.html

Attempting in Plex Web App results in:

> Error loading player:
> No playable sources found

Attempting in iOS results in a "-12880" error, which is common when the content is unavailable.

**Comment by sander1** [comment]
Closed due to inactivity. Youku has been removed from the Service bundle a long time ago.
