### ISSUE TITLE
SoundCloud service does not handle private track media objects

### ISSUE THREAD

**Issue by joshka** [plexinc-plugins/Services.bundle#778]
Hi,
I've written support for being able to view your own stream and tracks in the SoundCloud plugin.
This means that the user is logged in and may have access to private tracks. They need to pass through a token (currently stored in Dict) in order to get this access to the track. I'm not sure yet quite what the right way to handle this is. It seems like a little bug that we're take a track url that works i.e. soundcloud.com/track/123?oauth_token=XXX and make it not work by stripping that back to just the track.

**Comment by shopgirl284** [comment]
Since this channel and URL service has been removed, this issue could be closed
