### ISSUE TITLE
Req - Higher bitrates for CW channel 

### ISSUE THREAD

**Issue by jbaconbits** [plexinc-plugins/Services.bundle#832]
CW currently offers  bitrates of 2100kbs on their official site for current shows, but the Plex channel max is significantly lower.

**Comment by sander1** [comment]
Hi!
How/where did you find that the bitrate is 2100kbs? I can only find bitrates up to 900kbps...

**Comment by jbaconbits** [comment]
Their video player lists 2100kbs.

​

**Comment by sander1** [comment]
Just to add some info to this: Higher bitrates are available in the Apple HTTP Live Stream format.. This stream can be found by changing the partner id to `132`. The HLS version is encrypted, so not each and every Plex client can play this version of the video.

**Comment by sander1** [comment]
Switched from RTMP to encrypted HLS in https://github.com/plexinc-plugins/Services.bundle/commit/8f95fdf46a0ac93f85105e118933e8381d976685

This also provides higher bitrate videos, but will not work in certain Plex clients for the moment due to encryption on the streams.
