### ISSUE TITLE
GiantBomb.com channel not providing audio/video codec information

### ISSUE THREAD

**Issue by jbaconbits** [plexinc-plugins/Services.bundle#837]
It looks like the channel does not provide codec info, causing some clients to do an unnecessary transcode on files that should otherwise directplay. 

Noted here by a Plex dev.
https://forums.plex.tv/discussion/comment/1047807/#Comment_1047807

**Comment by sander1** [comment]
duplicate
--> https://github.com/plexinc-plugins/GiantBomb.bundle/issues/15
