### ISSUE TITLE
Plex Deletes Plugin Folder on Start

### ISSUE THREAD

**Issue by saturdaynight** [plexinc-plugins/Services.bundle#842]
Hi, this may sound really dumb but when I install the plugin and then restart Plex, it deletes the plugin folder.

Am I doing something wrong or is there a fix?

Thanks

Sat

**Comment by sander1** [comment]
Since a couple of versions of Plex Media Server the core bundles (including Services.bundle) are no longer put in the Plug-ins folder, but kept inside the Plex Media Server executable.
