### ISSUE TITLE
Move services back to their associated channels for quicker update cycle.

### ISSUE THREAD

**Issue by mikedm139** [plexinc-plugins/Services.bundle#848]
Due to the bundling and locking of the Services.bundle with PMS releases, channels which rely on URL Services (pretty much all of them) will often go weeks without a fix. It is well understood that the process whereby the Services.bundle was auto-updated could result in a corrupt bundle and therefore unbundling  is not really an option. However, if the service code is maintained within the respective channel bundles which rely on it, that allows for a much quicker release cycle and better channel experience for users. Then if a channel bundle occasionally gets corrupted during the update process, it only affects the one channel and does not kill the entire channel experience for the user. The repair process should be as simple as having the user uninstall and reinstall the channel via the web interface rather than dig into the application support directory to remove the corrupt Services.bundle.

Since WatchLater content relies on a fully functional Services.bundle hosted on the node, and the node can be updated (essentially) at will without waiting for a PMS release, it is not reasonable to completely remove the service code from the Services.bundle. Nor, does it make sense to maintain the code in two (or more) separate places.

As such, I propose that we use git's `subtree` support to link the services code from the relevant channel bundles to the Services.bundle as one would for dependencies. This allows for the best all around support with only minor increase in management effort.
* Services.bundle still bundled with PMS to avoid potential corruption
* Channels include their own Services dependencies
  * improves turn around time on fixes for channels
  * limits potential interruption due to bundle corruption
  * relatively easy fix for bundle corruption
* Service code is still included in the Services.bundle via a `git subtree`
  * no need to maintain 2 code bases
  * updating the Services bundle with new code from the channel bundle maintains git history and is as easy as `git pull -s subtree <identifier> <branch>`

The biggest drawback I can see to the whole proposal is the actual conversion itself would be tedious and time consuming. Therefore, I wrote a bash script to handle the conversion quickly and with limited interaction. I uploaded the script to a [gist](https://gist.github.com/mikedm139/27344eb58f89ff2d4961) for review.
It is statically linked to the `plexinc-plugins` repositories and therefore needs to be run by someone with push access. Best if it's run from an empty directory as it will clone all the necessary git repos in the same directory.  It provides the following options:
```
# OPTIONS:
#  -h --help: show this message
#  -l --live: script will commit and push to "master" branches of plugin and service bundles
#  -t --test: script will commit and push to "massive_restructure" branches of plugin and service bundles
``` 

Tagging for discssion:
@mmccurdy @elan @sander1 @Gerk

**Comment by Gerk** [comment]
At a quick glance it looks great to me.  Taking this approach will certainly help improve the user's channel experience and allow us to be able to react quickly to the quickly changing web based video realm, and it still falls within the current framework's design which is win/win.

**Comment by elan** [comment]
> channels which rely on URL Services (pretty much all of them) will often go weeks without a fix

These channels should use node-based services (assuming they don't already), which would probably just take a small Framework tweak, cc: @jam. That is probably an easier solution, as long as clients respect the key URL change.

**Comment by mikedm139** [comment]
We discussed that possibility in #channel-developers. A couple of concerns that came up are:
* high traffic from one (or few) node IP(s) raising red flags with content providers and risking getting banned.
* geo-restrictions affecting content availability for users due to US-based node IP address(es).

**Comment by elan** [comment]
Ah yep, those are valid concerns.

The polar opposite would be to avoid "freezing" the services bundle.

**Comment by sander1** [comment]
There's one more issue with moving services back into the channel bundles: services (like YouTube or Vimeo) can no longer be shared amongst channels, unless the "other" channel (YouTube or Vimeo) is also installed om the user's system.

**Comment by mikedm139** [comment]
That's not entirely true. If, as proposed, the services actually live in
both places, then they can still be shared. The concern might rather be
that how things will interact if the service exists twice in the system.
Especially if due to the delay in PMS release vs channel release, one is
out of date.

**Comment by sander1** [comment]
I don't know what happens/if it's possible to have more than 1 URL Service with the same identifier...?

**Comment by Gerk** [comment]
That would be worth checking.  From my sketchy memory it will look for a local service first, then fall back to the Services.bundle.  It should be easy enough to figure this out looking at the Framework.bundle in theory.  If it doesn't stack like that but could it should resolve this potential issue.

**Comment by shopgirl284** [comment]
Could just the Services.bundle be moved back to the Plugins folder while the rest of the bundles are protected in the Resources folder?

It used to be that if the Services.bundle was corrupt, you would get an error message that mentioned the Services.bundle could not be updated when you did a "Check for Updates" from the Channel Directory. And deleting the Services.bundle then restarting Plex would replace that corrupted bundle.

If you could move just the Services.bundle back to the Plugins folder and still diagnose and fix it the issue the way I described above, we could just create a support document detailing that for users who have an issue with playback on multiple channels. 

I know the corruption of the Services.bundle is an issue and it is always best to fix an issue if you can. But if it is an issue that doesn't occur that often and keeping the issue from occurring causes more problems, it seems like it would be simpler to just offer a way to diagnose and fix the issue when it does occurs.

**Comment by shopgirl284** [comment]
This can probably be closed too since Services.bundle is back in the plugins folder
