### ISSUE TITLE
PBS.org site not working with PlexIT!

### ISSUE THREAD

**Issue by BigWheel88** [plexinc-plugins/Services.bundle#853]
Getting cannot find any videos message when trying to PlexIT one from PBS.org  http://www.pbs.org/video/2365609815/

http://forums.plex.tv/discussion/198537/newbie-question-about-why-plex-it-does-not-seem-to-work#latest

If it cannot work then we need to remove from [supported sites page](https://support.plex.tv/hc/en-us/articles/200690288-Supported-Plex-It-Websites)

**Comment by sander1** [comment]
Finally fixed with https://github.com/plexinc-plugins/Services.bundle/compare/fc796a6a98c5ca84b10c026c9cf4c155384754a3...a544da042bea67dfc757de023ec87a6295d1a440
