### ISSUE TITLE
Food Network Canada media not currently available error

### ISSUE THREAD

**Issue by Bolter11** [plexinc-plugins/Services.bundle#857]
Perhaps needs a link update - shows current (up to date) episodes but error occurs when trying to play

**Comment by sander1** [comment]
Not part of Services bundle, but probably fixed within the channel:

https://github.com/plexinc-plugins/FoodNetworkCanada.bundle/commit/b5e7744ac0b1ae16e988d38baf9d5730291fa885

https://github.com/plexinc-plugins/FoodNetworkCanada.bundle/commit/7b8371da9a3eb33d572d21fdb9cc4406a33a13e6

**Comment by Bolter11** [comment]
I apologize but I don't understand the comment  -this is still not fixed...
