### ISSUE TITLE
NPO urls with multiple _

### ISSUE THREAD

**Issue by yutzhead** [plexinc-plugins/Services.bundle#858]
The NPO url service expects urls that end in /ABC_123. 

This breaks for http://www.npo.nl/kijken-naar-bosch/23-01-2016/REG_BRAB_TV2173217, where multiple underscores are present, and chars and numbers are mixed in the last element.

```
^http:\/\/(www\.)?npo\.nl\/[^/]+\/[0-9]{2}\-[0-9]{2}\-[0-9]{4}\/.+\d+
```
catches those, too.

**Comment by sander1** [comment]
Hi!
Thanks for the heads up! This has been updated in https://github.com/plexinc-plugins/Services.bundle/commit/b658ed384b55c48532ca9a10a95dcf5503acb918
