### ISSUE TITLE
CNET TV - Roadshow videos are causing URL service errors

### ISSUE THREAD

**Issue by shopgirl284** [plexinc-plugins/Services.bundle#862]
Videos for the Roadshow are now "http://www.cnet.com/roadshow/videos/..." instead of the "http://www.cnet.com/videos/..." pattern used by other videos on the CNET website. 

Need to see if this just requires a change to the Regex of the URL pattern or if the Roadshow portion of CNET handles their video pages differently.

**Comment by sander1** [comment]
Already fixed :) https://github.com/plexinc-plugins/Services.bundle/commit/91b9b92d8acd3ad5cd0811c68038da490a93ffdd

**Comment by shopgirl284** [comment]
Sorry. I check the closed PRs instead of commits.
