### ISSUE TITLE
Bundle in Plex Media Server does not contain correct version?

### ISSUE THREAD

**Issue by meriko** [plexinc-plugins/Services.bundle#869]
Just downloaded PMS 0.9.15.6.1714-7be11e1

In the Plug-ins-7be11e1 directory the Servicecode.pys file for dplay contains the line:
```
timestamp = (int(Datetime.Now().strftime("%s"))+3600)*1000
```

which indicates it's not the correct version that is used?

This line was updated in:
https://github.com/plexinc-plugins/Services.bundle/commit/32baac5bc8fdb04c0a2d071ce593506fd5a0e86e

**Comment by maxGreenblatt** [comment]
The Services.bundle that is bundled with PMS is currently updated periodically and not automatically updated with each check-in to this repo.

We are working on a fix to this, so that services will update much more frequently.

**Comment by meriko** [comment]
Ok, I thought it was updated with each PMS update.
Thanks for the explantation!
