### ISSUE TITLE
CW videos no longer play

### ISSUE THREAD

**Issue by shopgirl284** [plexinc-plugins/Services.bundle#874]
There is not an error in the URL service, but the Plex player says the video is no longer available. The videos play from the CW website.

**Comment by sander1** [comment]
Switched from RTMP to encryoted HLS in https://github.com/plexinc-plugins/Services.bundle/commit/8f95fdf46a0ac93f85105e118933e8381d976685

Also closing https://github.com/plexinc-plugins/Services.bundle/issues/832
