### ISSUE TITLE
beeg video urls incorrect

### ISSUE THREAD

**Issue by sander1** [plexinc-plugins/Services.bundle#878]
Something has changed and the final video URLs are incorrect, breaking video playback.

**Comment by LastEmprah** [comment]
Yes, their API url has changed yet again. You can see more info on https://github.com/rg3/youtube-dl/commit/5299bc3f91ffbb784addaee002611a52232134a1

**Comment by sander1** [comment]
Updated in https://github.com/plexinc-plugins/Services.bundle/commit/a81cdcb144598a3961f9bd8a8ef5f0c05ef72127
