### ISSUE TITLE
ABC direct play on ATV4 and iOS not working.

### ISSUE THREAD

**Issue by jocoman** [plexinc-plugins/Services.bundle#885]
With direct play enabled ABC is the only channel of the major broadcast channels that I use (CBS, NBC, FOX, CW) that will not play content.  The channel launches and I can view and select content.  However, when launched the ring spins a couple of times and then goes back to the content list without playing.  This does not happen on the Roku client.  Direct play works fine there.  ABC on ATV4 will play if direct play is disabled but the video quality suffers.  This either has to be a specific ATV4 client issue, or there is some broken code in the channel or the services.bundle file.  Will you please investigate this issue?  Thanks.

**Comment by jocoman** [comment]
This issue does not appear to be resolved.  ATV still will not play any content from the ABC channel.  The spinning dashes appear but then it crashes back to the show listing.

**Comment by sander1** [comment]
I didn't close this issue because it's been fixed, I closed it because it's a duplicate issue.

**Comment by jocoman** [comment]
Ok. I just said closed, so I assumed that meant the issue had been resolved.

On Thu, Jun 9, 2016 at 4:02 PM Sander Spies <notifications@github.com>
wrote:

> I didn't close this issue because it's been fixed, I closed it because
> it's a duplicate issue.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/plexinc-plugins/Services.bundle/issues/885#issuecomment-225025688>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/APVy86ZKpYA1QKL-rwK6sRwARTSikWl0ks5qKH94gaJpZM4H2ojA>
> .
>
-- 
Chris Yarbrough

**Comment by sander1** [comment]
ABC has been updated, both the channel code and the Services.bundle code. Both updates have been pushed out to the Channel Directory. Please let me know if the new version of the channel works on Apple TV.
