### ISSUE TITLE
URL Service for TWiT appears to be broken

### ISSUE THREAD

**Issue by sbucholtz** [plexinc-plugins/Services.bundle#907]
MetadataObjectForURL throws an exception for what appears to be a problem with the 302 redirect by the site to HTTPS. It looks like some kind of SSLv3 handshake problem.

Live channel streams properly. but it is not possible to watch any back episodes.

**Comment by sander1** [comment]
(Temporarily) fixed with https://github.com/plexinc-plugins/Services.bundle/commit/333a1bd389fb68c66d7f843867841ccf904e33b8
