### ISSUE TITLE
Vimeo

### ISSUE THREAD

**Issue by shopgirl284** [plexinc-plugins/Services.bundle#908]
Director pull in MetadatforURL causing issue with some videos.

Ex. https://vimeo.com/170793958

**Comment by shopgirl284** [comment]
The issue appears to be with the director attribute. Does that no longer work? Because I get the same error with the Crackle channel. If so, the director attribute is used in 3 URL services and should be removed from all of them. Crackle, Vimeo, and TouTV

**Comment by sander1** [comment]
Yeash, look like _something_ has changed. I've removed the directors/writers from Vimeo, TOU and Crackle.
