### ISSUE TITLE
Correct released version?

### ISSUE THREAD

**Issue by meriko** [plexinc-plugins/Services.bundle#923]
Don't know if this is a problem, but according to:

http://nine.plugins.plexapp.com/apps/all.json
the current version is bee5764

According to https://plugins.plex.tv/apps/all.json
the current version is ad3560c

Which one is correct? The latter is 21 days old and therefore lacks a lot of corrections, and it's this URL that my PMS uses to check for updates(according to com.plexapp.system.log) ...

**Comment by sander1** [comment]
> http://nine.plugins.plexapp.com/apps/all.json

This is the "old" location, used by PMS versions < 1.

> According to https://plugins.plex.tv/apps/all.json the current version is ad3560c

This one has just been updated.

**Comment by meriko** [comment]
Aha, ok!

Thanks!
