### ISSUE TITLE
Release version

### ISSUE THREAD

**Issue by meriko** [plexinc-plugins/Services.bundle#926]
Any chance to release a new version soon? My mistake in https://github.com/plexinc-plugins/Services.bundle/commit/8ce6af22a36a0daa6d67226b029ee40d1d9c5a23 was rectified in https://github.com/plexinc-plugins/Services.bundle/commit/431343a618ac049ca25fca9b4d3c058105da1edc . There are many people waiting for an update:
https://forums.plex.tv/discussion/comment/1269896/#Comment_1269896

**Comment by sander1** [comment]
Done!

**Comment by meriko** [comment]
Thanks @sander! 👍

**Comment by meriko** [comment]
@sander1 
Don't know if PMS < V1.0 is still supported? One user has v0.9.11.x due to LG MediaLink not working with latest version. Can the http://nine.plugins.plexapp.com/apps/all.json also be updated to latest GitHub version?

**Comment by meriko** [comment]
Thanks again @sander1 !
