### ISSUE TITLE
Comedy Central plugin plays low quality video for the first "segment"

### ISSUE THREAD

**Issue by jmbrysk** [plexinc-plugins/Services.bundle#959]
Video quality on streaming video seems to use a "low bandwidth" setting for the first block of streaming video before switching to HD. This issue appears on the Plex server as well as my PS4 client.

**Comment by sander1** [comment]
I've seen this before, but this doesn't seem to be an issue with the URL Service, but with the Plex client or server not starting with or switching to a higher bitrate version of the stream. The URL Service works as expected and provides the streaming URL. After that the URL Service is done and it's up to the client and server to determine how they are going to handle playback. There is nothing we can do from within the service code to change this.

**Comment by sander1** [comment]
Luckily there seems to be a way to fix this after all. Update https://github.com/plexinc-plugins/Services.bundle/commit/0441fa141f2ce306e0e5668cedd1ea8d9f670e71 should give better quality videos for CC. An update to the Service bundle will be released soon.
