### ISSUE TITLE
Ustream live feeds no longer work

### ISSUE THREAD

**Issue by shopgirl284** [plexinc-plugins/Services.bundle#968]
The current ustream URL service is no longer able to play live streams. 

It is unable to get the video id, but I altered the code to pull the video ID from the twitter embed code and the live streams still do not play. Even with the embed ID it returns an error opening the http://iphone-streaming.ustream.tv URL.

**Comment by sander1** [comment]
This service has been broken for some time. It's not easy to fix, so it's been removed from the bundle.

**Comment by shopgirl284** [comment]
Since this channel has been removed. Closing this issue
