### ISSUE TITLE
Lifetime videos no longer play

### ISSUE THREAD

**Issue by shopgirl284** [plexinc-plugins/Services.bundle#970]
Receiving media not available errors for any videos in the Lifetime channel.

There seems to be an issue with the GetSMIL function causing it to return Media Not Available on line 149.

**Comment by eetjtl** [comment]
didn't sanders1 fix that 3 days ago ?

**Comment by sander1** [comment]
I've only fixed a part of the issue: finding the correct feed URL.

**Comment by shopgirl284** [comment]
See PR 971 - https://github.com/plexinc-plugins/Services.bundle/pull/971
