### ISSUE TITLE
Comedy Central / South Park channels throwing error: Conversion failed. The transcoder crashed or failed to start up.

### ISSUE THREAD

**Issue by krunk4ever** [plexinc-plugins/Services.bundle#976]
Keep getting the follow error when trying to play anything via the Comedy Central channel plugin.

> Conversion failed. The transcoder crashed or failed to start up.

Not seeing any problems with any other channels or personal media.

I've attached the logs here: https://gist.github.com/krunk4ever/2c0f78571c379915b9ce828b810fd7c7#file-plex-log

Currently running Plex Server Version 1.7.6.4058 on a QNAP TS-451+

**Comment by sander1** [comment]
You're better of checking/posting the Plex Media Server.log and ask in the PMS/Qnap forum (https://forums.plex.tv/categories/qnap). This doesn't seem to be a CC channel or service issue.
