### ISSUE TITLE
TWiT Live Stream stopped working on Plex 

### ISSUE THREAD

**Issue by sbucholtz** [plexinc-plugins/Services.bundle#992]
Sometime in the last month or two the Live Stream stopped working when playing it on my Plex app running on Tivo, running the Plex web application on Edge, and running the Plex Android application.

Looking on the Plex Server I see the following log entries:
Sep 27, 2017 11:03:09.065 [0x2af196600700] ERROR - HTTP 404 downloading url http://127.0.0.1:32400/video/twittv/:/function/LiveStream?function_args=Y2VyZWFsMQoxCmRpY3QKMgpzMTEKRmxvc29mdC5iaXpzMTIKaGxzX3Byb3ZpZGVyYjFzMTcKaW5jbHVkZV9jb250YWluZXJyMAo_&includeBandwidths=1&X-Plex-Session-Identifier=ijn79nt5zd0g3ban5i2cpu8f
Sep 27, 2017 11:03:09.065 [0x2af196600700] ERROR - TranscodeUniversalRequest: unable to get container: /video/twittv/:/function/LiveStream?function_args=Y2VyZWFsMQoxCmRpY3QKMgpzMTEKRmxvc29mdC5iaXpzMTIKaGxzX3Byb3ZpZGVyYjFzMTcKaW5jbHVkZV9jb250YWluZXJyMAo_&includeBandwidths=1&X-Plex-Session-Identifier=ijn79nt5zd0g3ban5i2cpu8f

**Comment by sander1** [comment]
Their wiki says

> Flosoft disappeared without any warning in September 2017. All attempts to contact them have gone unanswered. At this point, we're pretty much assuming they've been abducted by aliens.

I'll see if we can add a different live feed to the channel.

**Comment by sander1** [comment]
Replaced by UStream (updated in channel bundle).
