### ISSUE TITLE
cnettv URL services issue

### ISSUE THREAD

**Issue by shopgirl284** [plexinc-plugins/Services.bundle#993]
The URL service for CNET is producing errors.

All videos are returning a "Media Not Available" error on line line 70 in the PlayVideo video function.

The regex used on line 65 does not appear to pull the video_url value properly.

**Comment by sander1** [comment]
Fixed in https://github.com/plexinc-plugins/Services.bundle/commit/c0243c22ab8bbdda716e72bebd9566e15afc715b
