### ISSUE TITLE
CBS URL service video not showing in queue

### ISSUE THREAD

**Issue by dough321** [plexinc-plugins/Services.bundle#995]
Trying to add below URLs by email to my watch later queue. Videos are not showing
http://www.cbs.com/shows/kevin-can-wait/video/pO1CdrK2Nie_PjfRCKr4i1Ga5wBk0mI7/kevin-can-wait-the-might-ve-before-christmas/
http://www.cbs.com/shows/bull/video/42qVsQj_B3NoXBRogGYGMP8so5LVo5xE/bull-home-for-the-holidays/
Removing last part after video ID didn't help either.
http://www.cbs.com/shows/kevin-can-wait/video/pO1CdrK2Nie_PjfRCKr4i1Ga5wBk0mI7

**Comment by sander1** [comment]
The bookmarklet also fails... It looks like CBS has blocked the node server from accessing their content :(
