### ISSUE TITLE
PBS URL service shared code failing

### ISSUE THREAD

**Issue by shopgirl284** [plexinc-plugins/Services.bundle#997]
Receiving a 401 error when trying to produce sections from the PBS plugin on line 77.

The issue appears to be with the SharedCodeService portion of the PBS URL service that provides the code necessary to access the Cove API used by PBS

**Comment by shopgirl284** [comment]
The SharedCodeService is used for the API access code which was written a long time ago. And I think there is a registration required to access the PBS API.

More research would need to be done into what has changed about the API access code, but this does not appear to be an issue that will be easy to fix

**Comment by sander1** [comment]
FYI: The CoveAPI has been discontinued: https://docs.pbs.org/display/coveapi

**Comment by shopgirl284** [comment]
The PBS plugin will have to be completely rewritten.

See https://github.com/plexinc-plugins/PBS.bundle/issues/30

**Comment by shopgirl284** [comment]
See https://github.com/plexinc-plugins/Services.bundle/commit/956d50f4b98fccc0be3c2eb4aa75a9e09141b2dd
